apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq1
  namespace: bank-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "450Mi"
    limits.cpu: "3"
    limits.memory: "2Gi"
    services.loadbalancers: "2"