apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq1
  namespace: bank-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "250Mi"
    limts.cpu: "2"
    limits.memory: "1Gi"
    service.loadblancers: "2"