apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-stateful
spec:
  serviceName: mysqldb
  replicas: 1
  selector:
    matchLabels:
      app: blood-db
  template:
    metadata:
      labels:
        app: blood-db
        namespace: bank-dev
    spec:
      containers:
      - name: cont1
        image: 967848863323.dkr.ecr.us-east-1.amazonaws.com/blood-db:2
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name:  secret
        resources:
          limits:
            memory: "250Mi"
            cpu: "700m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        volumeMount:
          - name: mysql-vol
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-vol
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2
        resources:
          requests:
            storage: 2Gi